# Generated by Django 4.1.1 on 2022-09-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='games',
        ),
        migrations.AddField(
            model_name='game',
            name='users',
            field=models.ManyToManyField(blank=True, to='core.profile'),
        ),
    ]
