# Generated by Django 4.1.1 on 2022-09-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_profile_games_game_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='users',
        ),
        migrations.AddField(
            model_name='profile',
            name='games',
            field=models.ManyToManyField(blank=True, to='core.game'),
        ),
    ]
